name = "kamitakada-seikotsuin"
compatibility_date = "2026-09-01"

main = "./dist/worker/index.js"

[assets]
directory = "./site"

[[d1_databases]]
binding = "DB"
database_name = "kamitakada-reservation"
database_id = "311aa743-57d1-45cc-b222-61644496ef32"

